variables:
    projects: "getting-started,refactored-solution"

image: maven:3.6.3-openjdk-15

test:
    script: "mvn clean test -B -pl $projects"
    
build:
    script: "mvn clean package -B -pl $projects"
